### ISSUE TITLE
Questions regarding "A Survival Model in Stan".

### ISSUE THREAD

**Issue by dukechain2333** [ermeel86/ermeel86.github.io#1]
Hi Eren!

I am visiting your site: https://ermeel86.github.io/case_studies/surv_stan_example.html

I have a question: your equation on the page seems to have no relationship with time t. How did you acquire this picture?

<img width="868" alt="image" src="https://github.com/ermeel86/ermeel86.github.io/assets/57356723/ed8448e7-4354-4b97-94bf-66288ad4356b">

It would be very helpful if you could share some thoughts with me.

**Comment by ermeel86** [comment]
Hi William,

Since the baseline hazard is time independent, one can derive the two survival curves (as a function of time) for this case study simply by exponentiating $-t$ times the respective constant hazard.

I try to add a short remark to the case study, when I find time.

Best,
Eren.

**Comment by dukechain2333** [comment]
Thank you!
