### ISSUE TITLE
The Deduction on Posterior

### ISSUE THREAD

**Issue by dukechain2333** [ermeel86/ermeel86.github.io#2]
Hi!

I was working on the Cox model with a Bayesian perspective, and I really struggled with the likelihood of censored and uncensored data. I tried your method and found it to be working very well. However, the deduction of this posterior is not very clear in your post (https://ermeel86.github.io/case_studies/surv_stan_example.html). 

Could you send me any reference on how you deduct your liklihood and posterior? I will be very appreciative of that.

Thank you!

**Comment by ermeel86** [comment]
Sure. 

I can recommend https://grodri.github.io/glms/notes/c7s2, particularly section 7.2.2. and the example, contained therein. 

Please let me know, whether this helped.

**Comment by dukechain2333** [comment]
Sorry for the late reply. It was a great help. Thank you!
